"""toying with player and User relationship

Revision ID: 91bab41d4b7b
Revises: ab48785e5b6d
Create Date: 2024-02-13 22:24:54.200371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bab41d4b7b'
down_revision = 'ab48785e5b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_player_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('fk_player_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
